
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kedvsbbluwsnkposzaqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlZHZzYmJsdXdzbmtwb3N6YXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MDc0NjUsImV4cCI6MjA1NjI4MzQ2NX0.cZSkN8gtC6SYZ3ksA1aK7rK6soXJ0Fkkd3x5ID79Mac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
